package com.bridgelabz.iplanalyser.utility;

public enum SortField {
    AVERAGE, STRIKE_RATE, SIXES_AND_FOURS, AVERAGE_WITH_STRIKERATE, MAXIMUM_RUNS_WITH_BEST_AVERAGE,
    FOURS_AND_SIXES_WITH_STRIKERATE, BEST_BOWLING_AVERAGE, MAXIMUM_RUNS
}
